# Generated by Django 4.1.5 on 2023-01-16 01:00

import os

from django.db import migrations
from dotenv import load_dotenv

load_dotenv()


def initial_data(apps, schema_editor):
    Font = apps.get_model("app", "Font")
    fonts = [
        Font(name="Calibri", url="https://fonts.googleapis.com/css?family=Calibri:400,700,400italic,700italic"),
        Font(name="Rubik", url="https://fonts.googleapis.com/css2?family=Rubik:wght@400;700"),
    ]
    Font.objects.bulk_create(fonts)


def create_superuser(apps, schema_editor):
    from django.contrib.auth.models import User
    from django.utils import timezone

    EMAIL = os.getenv("ADMIN_EMAIL", "admin@gmail.com")
    PASSWORD = os.getenv("ADMIN_PASSWORD", "admin")

    User.objects.create_superuser(username="admin", email=EMAIL, password=PASSWORD, last_login=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
        migrations.RunPython(initial_data),
    ]
